service: bikeroutes

provider:
  name: aws
  region: eu-south-1
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  profile: AWS-LAMBDA

functions:
  githubWebhookListener:
    handler: serverBuild/server/server.getRoutesListener
    events:
      - http:
          path: /
          method: get
          cors: true
