service: bikeroutes

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  profile: AWS-LAMBDA

functions:
  githubWebhookListener:
    handler: serverBuild/server/server.getRoutesListener
    events:
      - http:
          path: /
          method: get
          integration: lambda
          cors: true
